const ADD_TO_CART = "ADD_TO_CART";
const INCREASE_QUANTITY = "INCREASE_QUANTITY";
const DECREASE_QUANTITY = "DECREASE_QUANTITY";
const CONFIRM_ORDER = "CONFIRM_ORDER";

export { ADD_TO_CART, INCREASE_QUANTITY, DECREASE_QUANTITY, CONFIRM_ORDER };
